// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm471nY5bsZNysove66xxloig0m_IeE1M',
    appId: '1:120953432298:web:09853d1ec26d06dc1a8f93',
    messagingSenderId: '120953432298',
    projectId: 'prakflutterfirebase-5a5e0',
    authDomain: 'prakflutterfirebase-5a5e0.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-5a5e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy69Da9VcOw8yFTibqd88NcKL6UhhA0q0',
    appId: '1:120953432298:android:3c535466c6b2582e1a8f93',
    messagingSenderId: '120953432298',
    projectId: 'prakflutterfirebase-5a5e0',
    storageBucket: 'prakflutterfirebase-5a5e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD6Ybwek0Rm8iwPAsipcwZswfl2lorSfs',
    appId: '1:120953432298:ios:ccf3a825aa6aac621a8f93',
    messagingSenderId: '120953432298',
    projectId: 'prakflutterfirebase-5a5e0',
    storageBucket: 'prakflutterfirebase-5a5e0.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD6Ybwek0Rm8iwPAsipcwZswfl2lorSfs',
    appId: '1:120953432298:ios:ccf3a825aa6aac621a8f93',
    messagingSenderId: '120953432298',
    projectId: 'prakflutterfirebase-5a5e0',
    storageBucket: 'prakflutterfirebase-5a5e0.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm471nY5bsZNysove66xxloig0m_IeE1M',
    appId: '1:120953432298:web:6d52aaa6d4eaccdb1a8f93',
    messagingSenderId: '120953432298',
    projectId: 'prakflutterfirebase-5a5e0',
    authDomain: 'prakflutterfirebase-5a5e0.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-5a5e0.appspot.com',
  );
}
